name: CI/CD Security Pipeline

on:
  push:
    branches: [main]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Scan Trivy sur image nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Login Harbor
        run: |
          docker login 172.18.0.2:30002 -u admin -p Harbor12345

      - name: Tag et Push vers Harbor
        run: |
          docker pull nginx:latest
          docker tag nginx:latest 172.18.0.2:30002/nginx-app/nginx:${{ github.sha }}
          docker push 172.18.0.2:30002/nginx-app/nginx:${{ github.sha }}
