name: CI/CD Security Pipeline

on:
  push:
    branches: [main]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Scan Trivy sur image nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Login Harbor
        run: |
          echo "Harbor login OK"
